[package]
name = "bevygame"
version = "0.1.0"
authors = ["Martin Tang <martin.tang@oaknorth.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3.0"
